CREATE TABLE archiwum_zamowien (
    archiwum_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zamowienie_id NUMBER,
    klient_id NUMBER,
    data_zamowienia DATE,
    status VARCHAR2(20),
    data_archiwizacji DATE DEFAULT SYSDATE
);