CREATE TABLE logi (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabela_nazwa VARCHAR2(50),
    operacja VARCHAR2(20),
    rekord_id NUMBER,
    data_operacji TIMESTAMP DEFAULT SYSTIMESTAMP,
    uzytkownik VARCHAR2(50) DEFAULT USER,
    szczegoly CLOB
);