CREATE TABLE podsumowania_sprzedazy (
    podsumowanie_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    typ VARCHAR2(20) CHECK (typ IN ('MIESIECZNE', 'KWARTALNE', 'ROCZNE')),
    okres VARCHAR2(7), -- np. '2025-01', '2025-Q1', '2025'
    kategoria VARCHAR2(50),
    liczba_zamowien NUMBER,
    suma_sprzedazy NUMBER(15,2),
    data_generacji DATE DEFAULT SYSDATE
);