CREATE TABLE pozycje_zamowien (
    pozycja_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zamowienie_id NUMBER REFERENCES zamowienia(zamowienie_id) ON DELETE CASCADE,
    produkt_id NUMBER REFERENCES produkty(produkt_id),
    ilosc NUMBER NOT NULL CHECK (ilosc > 0),
    cena_sprzedazy NUMBER(10,2) NOT NULL
);