CREATE TABLE produkty (
    produkt_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa VARCHAR2(200) NOT NULL,
    kategoria VARCHAR2(50) CHECK (kategoria IN ('Laptop', 'Telefon', 'Tablet', 'Akcesoria', 'Audio')),
    cena NUMBER(10,2) NOT NULL CHECK (cena > 0),
    stan_magazynowy NUMBER DEFAULT 0,
    dostawca_id NUMBER REFERENCES dostawcy(dostawca_id)
);