CREATE TABLE sprzedaz (
    sprzedaz_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zamowienie_id NUMBER UNIQUE REFERENCES zamowienia(zamowienie_id),
    data_sprzedazy DATE DEFAULT SYSDATE,
    kwota_total NUMBER(15,2)
);