CREATE TABLE dostawcy (
    dostawca_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa VARCHAR2(100) NOT NULL
);

CREATE TABLE produkty (
    produkt_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa VARCHAR2(200) NOT NULL,
    kategoria VARCHAR2(50),
    cena NUMBER(10,2),
    stan_magazynowy NUMBER,
    dostawca_id NUMBER REFERENCES dostawcy(dostawca_id)
);

CREATE TABLE logi (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operacja VARCHAR2(50),
    szczegoly VARCHAR2(255),
    data_operacji TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE archiwum_produktow (
    arch_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stara_nazwa VARCHAR2(200),
    stara_cena NUMBER,
    data_usuniecia DATE DEFAULT SYSDATE
);

CREATE TABLE podsumowania_sprzedazy (
    podsumowanie_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    okres VARCHAR2(7),
    kategoria VARCHAR2(50),
    suma_wartosci NUMBER(15,2)
);


INSERT INTO dostawcy (nazwa) VALUES ('Hurtownia Elektroniki S.A.');
INSERT INTO dostawcy (nazwa) VALUES ('Tech-Global Sp. z o.o.');
COMMIT;