CREATE TABLE zamowienia (
    zamowienie_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    klient_id NUMBER REFERENCES klienci(klient_id),
    data_zamowienia DATE DEFAULT SYSDATE,
    status VARCHAR2(20) DEFAULT 'NOWE' CHECK (status IN ('NOWE', 'W REALIZACJI', 'ZAKONCZONE', 'ANULOWANE'))
);